### ISSUE TITLE
Mix Failure at startup

### ISSUE THREAD

**Issue by janxious** [oestrich/grapevine#113]
Trying to follow the instructions for getting this working, I have exactly the required software versions specified. I see this:

```
[master] grapevine $ mix deps.get
** (CompileError) config/config.exs:1: module Config is not loaded and could not be found
    (elixir) lib/code.ex:232: Code.eval_string/3
    (mix) lib/mix/config.ex:220: Mix.Config.eval!/2
```

Is the assumption that one will set this up via vagrant or docker instead of locally?

• • • • •

I kind of expected a `bin/setup` or something similar to get started working on an issue. :)

**Comment by oestrich** [comment]
So far I'm almost the only one who has developed this so no need for `bin/setup` :smile:. This is assuming "native" development, no docker or vagrant. 

That said, this looks like an issue with not using Elixir 1.9. Are you using the versions in [.tool-versions](https://github.com/oestrich/grapevine/blob/master/.tool-versions)?

**Comment by janxious** [comment]
I double-checked my elixir version and it was the culprit. I think I just misread the information brew was giving to me. Sorry for the alarm. :(
