### ISSUE TITLE
Internal Server Error when trying to upload an image

### ISSUE THREAD

**Issue by mpconley** [oestrich/grapevine#125]
I made a simple image file for my test game Age of Elements and the page https://grapevine.haus/manage/games/157/edit presents an Internal Server Error when I upload the image file, which is a small PNG file, attached.

![aoe_grapevine](https://user-images.githubusercontent.com/3058178/72675934-840a7680-3a59-11ea-84be-72f126b7d851.png)

Could you take a look when you get a chance?

**Comment by oestrich** [comment]
Thanks for catching this, I think there's a build issue from my last push and the certs got all funky (unrelated to the other issue, as that was from my laptop.) The server can no longer talk to AWS so images can't be uploaded. I'll dig into this and figure it out. Thanks for letting me know!

**Comment by oestrich** [comment]
This should be fixed now. There was an issue with Erlang 22.2 and hackney which updating hackney fixed. Closing, but let me know if you still have problems.
