### ISSUE TITLE
Secure Telnet option not connecting

### ISSUE THREAD

**Issue by mpconley** [oestrich/grapevine#126]
I am able to securely telnet from Mudlet to my test game with ageofelements.org 8680.  This does not function for Grapevine at this time when I register this address into Grapevine.  This is not a high priority for me as normal telnet functions just fine, but I wanted to register the issue.  Thank you!

**Comment by oestrich** [comment]
Connecting locally shows this has an unknown CA, is this a self signed cert? If you have a self signed cert you can copy that into the cert field when creating/editing the secure connection. This should let you start to connect via TLS in the web client.

**Comment by mpconley** [comment]
The server has a Lets Encrypt cert and to my knowledge that’s what is fed into the setup of ‘stunnel’. I did not create any self-signed I am sure.  I will double check the config.

-Tamarindo

**Comment by mpconley** [comment]
Do you have a way to tell if the certificate you are seeing is the same one found on www.ageofelements.org from the browser?  It should be.  All of the config I do is buried at the very bottom of this page, https://github.com/age-of-elements/age-of-elements/, and it is pointing to the Let's Encrypt cert.  Thanks -Tamarindo

**Comment by mpconley** [comment]
A wee bit more information attached (the Secure info from a Mudlet connection).  This is me hoping it is on your side.  Again, not a high priority.  Thanks!

<img width="875" alt="Screen Shot 2020-01-23 at 12 34 21 PM" src="https://user-images.githubusercontent.com/3058178/73008565-cbd42980-3ddc-11ea-9b84-3fb625a6ac39.png">

**Comment by oestrich** [comment]
Yeah, I'm relatively certain it's on my end. I updated erlang versions which broke some stuff in a HTTP client (I think around certs), so it's highly likely that broke this. I can connect to midmud which uses lets encrypt though, which is even weirder. I'll keep poking at it as I update packages and get more current.

**Comment by mpconley** [comment]
I know StickMUD can connect securely now, so I am going to close this issue, thanks!
